"""Sentence labels shared by data building, training and inference."""

HUMAN = 0
AI = 1  # text generated by a language model (including "humanized" AI text)
REPHRASED = 2  # the student's own text, reworded/translated/heavily polished by a language model

LABEL_NAMES = ["human", "ai", "rephrased"]
NUM_LABELS = len(LABEL_NAMES)

# Token positions that must not contribute to the loss (separators, special tokens).
IGNORE_INDEX = -100
